const icons = {
  confused: '/icon/confused.png',
  devil: '/icon/devil.png',
  dizzy: '/icon/dizzy.png',
  faceMask: '/icon/face-mask.png',
  facePalm: '/icon/facepalm.png',
  flushed: '/icon/flushed.png',
  flushed2: '/icon/flushed2.png',
  grimacing: '/icon/grimacing.png',
  heartEyes: '/icon/heart-eyes.png',
  hello: '/icon/hello.png',
  hot: '/icon/hot.png',
  hugging: '/icon/hugging.png',
  joy: '/icon/joy.png',
  lying: '/icon/lying.png',
  nausea: '/icon/nausea.png',
  nerd: '/icon/nerd.png',
  neutral: '/icon/neutral.png',
  noMouth: '/icon/no-mouth.png',
  rage: '/icon/rage.png',
  rage2: '/icon/rage2.png',
  raised: '/icon/raised.png',
  sad: '/icon/sad.png',
  shy: '/icon/shy.png',
  sleeping: '/icon/sleeping.png',
  smile: '/icon/smile.png',
  sob: '/icon/sob.png',
  struck: '/icon/struck.png',
  thinking: '/icon/thinking.png',
  unamused: '/icon/unamused.png',
  yawn: '/icon/yawn.png',
};

export default icons;
