const icons = {
    running: "🏃",
    thinking: "🤔",
    coding: "💻",
    chatting: "💬",
    sleeping: "😴",
    eating: "🍴",
    driving: "🚗",
    swimming: "🏊",
    exercising: "🏋️",
    drinking: "🍹",
    walking: "🚶",
    studying: "📖",
    traveling: "✈️",
    shopping: "🛍️",
    cooking: "🍳",
    cleaning: "🧹",
    relaxing: "🛋️",
    angry: "😡",
    crying: "😭",
    smiling: "😊",
    laughing: "😂",
    showering: "🚿",
    working: "🖥️",
    typing: "⌨️",
    hiking: "🥾",
    fishing: "🎣",
    gaming: "🎮",
    painting: "🎨",
    gardening: "🌱",
    dancing: "💃",
  };
  
  export default icons;
  